insert into employees (id, first_name, last_name, email, gender) values (1, 'Isaac', 'Lamboll', 'ilamboll0@elegantthemes.com', 'M');
insert into employees (id, first_name, last_name, email, gender) values (2, 'Alidia', 'Caldow', 'acaldow1@blinklist.com', 'F');
insert into employees (id, first_name, last_name, email, gender) values (3, 'Kirsteni', 'Merveille', 'kmerveille2@ft.com', 'F');
insert into employees (id, first_name, last_name, email, gender) values (4, 'Jourdain', 'Marquand', 'jmarquand3@thetimes.co.uk', 'M');
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (5, 'Davidson', 'Nerheny', 'dnerheny4@europa.eu', 'M', 3);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (6, 'Andrea', 'Sturmey', 'asturmey5@vimeo.com', 'M', 2);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (7, 'Deane', 'Neem', 'dneem6@state.gov', 'M', 4);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (8, 'Charlotte', 'Preon', 'cpreon7@economist.com', 'F', 1);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (9, 'Timothee', 'Gabbitas', 'tgabbitas8@seesaa.net', 'M', 4);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (10, 'Ryann', 'Verrier', 'rverrier9@webeden.co.uk', 'F', 1);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (11, 'Garfield', 'Ettles', 'gettlesa@studiopress.com', 'M', 4);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (12, 'Raimundo', 'Wragge', 'rwraggeb@nytimes.com', 'M', 4);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (13, 'Auria', 'MacGuffie', 'amacguffiec@state.tx.us', 'F', 3);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (14, 'Mikaela', 'Mochar', 'mmochard@huffingtonpost.com', 'F', 1);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (15, 'Kincaid', 'Melton', 'kmeltone@ucla.edu', 'M', 4);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (16, 'Dru', 'Rubinsaft', 'drubinsaftf@cdc.gov', 'F', 2);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (17, 'Jennilee', 'Killingbeck', 'jkillingbeckg@cyberchimps.com', 'F', 4);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (18, 'Aurora', 'Benardeau', 'abenardeauh@digg.com', 'F', 4);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (19, 'Odelia', 'Bottomore', 'obottomorei@nps.gov', 'F', 2);
insert into employees (id, first_name, last_name, email, gender, supervisor_id) values (20, 'Noach', 'Rearden', 'nreardenj@edublogs.org', 'M', 4);
