INSERT INTO employees (first_name, last_name, email, password, gender) VALUES ('Isaac', 'Lamboll', 'ilamboll0@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M');
INSERT INTO employees (first_name, last_name, email, password, gender) VALUES ('Alidia', 'Caldow', 'acaldow1@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F');
INSERT INTO employees (first_name, last_name, email, password, gender) VALUES ('Kirsteni', 'Merveille', 'kmerveille2@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F');
INSERT INTO employees (first_name, last_name, email, password, gender) VALUES ('Jourdain', 'Marquand', 'jmarquand3@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M');
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Davidson', 'Nerheny', 'dnerheny4@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 3);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Andrea', 'Sturmey', 'asturmey5@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 2);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Deane', 'Neem', 'dneem6@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 4);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Charlotte', 'Preon', 'cpreon7@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 1);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Timothee', 'Gabbitas', 'tgabbitas8@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 4);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Ryann', 'Verrier', 'rverrier9@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 1);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Garfield', 'Ettles', 'gettlesa@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 4);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Raimundo', 'Wragge', 'rwraggeb@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 4);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Auria', 'MacGuffie', 'amacguffiec@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 3);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Mikaela', 'Mochar', 'mmochard@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 1);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Kincaid', 'Melton', 'kmeltone@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 4);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Dru', 'Rubinsaft', 'drubinsaftf@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 2);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Jennilee', 'Killingbeck', 'jkillingbeckg@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 4);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Aurora', 'Benardeau', 'abenardeauh@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 4);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Odelia', 'Bottomore', 'obottomorei@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'F', 2);
INSERT INTO employees (first_name, last_name, email, password, gender, supervisor_id) VALUES ('Noach', 'Rearden', 'nreardenj@ribas.pt', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm' 'M', 4);

INSERT INTO admins (email, password) VALUES ('admin@ribas.pto' '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm', '$2a$10$SPtCKntZ9.I9ZCSMtO3ewuDKrAeH1Te6nCGHyqT4V2WnXg7.7lHUm');
