insert into employees (first_name, last_name, email, gender) values ('Isaac', 'Lamboll', 'ilamboll0@elegantthemes.com', 'M');
insert into employees (first_name, last_name, email, gender) values ('Alidia', 'Caldow', 'acaldow1@blinklist.com', 'F');
insert into employees (first_name, last_name, email, gender) values ('Kirsteni', 'Merveille', 'kmerveille2@ft.com', 'F');
insert into employees (first_name, last_name, email, gender) values ('Jourdain', 'Marquand', 'jmarquand3@thetimes.co.uk', 'M');
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Davidson', 'Nerheny', 'dnerheny4@europa.eu', 'M', 3);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Andrea', 'Sturmey', 'asturmey5@vimeo.com', 'M', 2);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Deane', 'Neem', 'dneem6@state.gov', 'M', 4);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Charlotte', 'Preon', 'cpreon7@economist.com', 'F', 1);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Timothee', 'Gabbitas', 'tgabbitas8@seesaa.net', 'M', 4);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Ryann', 'Verrier', 'rverrier9@webeden.co.uk', 'F', 1);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Garfield', 'Ettles', 'gettlesa@studiopress.com', 'M', 4);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Raimundo', 'Wragge', 'rwraggeb@nytimes.com', 'M', 4);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Auria', 'MacGuffie', 'amacguffiec@state.tx.us', 'F', 3);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Mikaela', 'Mochar', 'mmochard@huffingtonpost.com', 'F', 1);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Kincaid', 'Melton', 'kmeltone@ucla.edu', 'M', 4);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Dru', 'Rubinsaft', 'drubinsaftf@cdc.gov', 'F', 2);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Jennilee', 'Killingbeck', 'jkillingbeckg@cyberchimps.com', 'F', 4);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Aurora', 'Benardeau', 'abenardeauh@digg.com', 'F', 4);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Odelia', 'Bottomore', 'obottomorei@nps.gov', 'F', 2);
insert into employees (first_name, last_name, email, gender, supervisor_id) values ('Noach', 'Rearden', 'nreardenj@edublogs.org', 'M', 4);
